var spritesData = [
    { frames: ['bunny0.png'] },
    { frames: ['bunny5.png'] },
    { frames: ['bunny0.png', 'bunny1.png'] },
    { frames: ['bunny2.png', 'bunny3.png'] },
    { frames: ['bunny4.png', 'bunny5.png'] },
    { frames: ['bunny0.png', 'bunny0.png', 'bunny0.png', 'bunny3.png'] },
    { frames: ['bunny0.png', 'bunny1.png', 'bunny0.png', 'bunny3.png'] },
    { frames: ['bunny4.png', 'bunny4.png', 'bunny4.png', 'bunny4.png', 'bunny5.png'] },
    { frames: ['bunny0.png', 'bunny0.png', 'bunny0.png', 'bunny1.png', 'bunny0.png', 'bunny0.png', 'bunny0.png', 'bunny0.png', 'bunny3.png'] },
    { frames: ['rat0.png'] },
    { frames: ['rat0.png', 'rat2.png'] },
    { frames: ['rat2.png', 'rat3.png'] },
    { frames: ['rat3.png', 'rat3.png', 'rat4.png'] },
    { frames: ['rat0.png', 'rat0.png', 'rat0.png', 'rat1.png'] },
    { frames: ['rat2.png', 'rat2.png', 'rat2.png', 'rat3.png'] },
    { frames: ['rat0.png', 'rat1.png', 'rat0.png', 'rat0.png', 'rat2.png'] },
    { frames: ['rat0.png', 'rat0.png', 'rat0.png', 'rat1.png', 'rat0.png', 'rat0.png', 'rat2.png', 'rat0.png', 'rat0.png', 'rat0.png', 'rat3.png'] },
    { frames: ['snail0.png']},
    { frames: ['snail0.png', 'snail1.png'], velocity: 0.02, animVelocity: 1/45 },
    { frames: ['bird0.png'] },
    { frames: ['bird0.png', 'bird3.png'] },
    { frames: ['bird0.png', 'bird1.png'] },
    { frames: ['bird0.png', 'bird0.png', 'bird1.png', 'bird0.png', 'bird0.png', 'bird0.png', 'bird3.png'] },
    { frames: ['bird0.png', 'bird4.png', 'bird0.png', 'bird5.png'], velocity: 0.02, animVelocity: 1/20 },
  ];

var cat = { frames: ['cat0.png'] }